AWSTemplateFormatVersion: 2010-09-09
Description: handle outbound messages from salesforce to update zuora and indentity
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: membership
  App:
    Description: Application name
    Type: String
    Default: salesforce-message-handler
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: membership-dist
Resources:
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  SQSPolicy:
      Type: AWS::IAM::Policy
      Properties:
          PolicyName: sqs-policy
          PolicyDocument:
              Statement:
                  - Effect: Allow
                    Action:
                        - sqs:SendMessage
                    Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:salesforce-outbound-messages-${Stage}.fifo"

          Roles:
              - !Ref ApiGatewayRole
  MessageHandlerApi:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
          Description: Api to handle salesforce outbound messages
          Name: !Sub salesforce-message-handler-${Stage}

  MessageHandlerApiResource:
      Type: AWS::ApiGateway::Resource
      Properties:
          RestApiId: !Ref MessageHandlerApi
          ParentId: !GetAtt [MessageHandlerApi, RootResourceId]
          PathPart: contact
      DependsOn: MessageHandlerApi

  ContactMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "POST"
        RestApiId: !Ref MessageHandlerApi
        ResourceId: !Ref MessageHandlerApiResource
        MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
        Integration:
          Credentials: !GetAtt ApiGatewayRole.Arn
          IntegrationHttpMethod: "POST"
          Type: "AWS"
          Uri: !Sub "arn:aws:apigateway:${AWS::Region}:sqs:action/SendMessage"
          RequestParameters:
            integration.request.querystring.QueueUrl: !Sub "'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/salesforce-outbound-messages-CODE.fifo'"
            integration.request.querystring.MessageGroupId: "'salesforce_outbound1'"
            integration.request.querystring.MessageBody:  "method.request.body"
          IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Content-Type: "'text/xml'"
            ResponseTemplates:
               text/xml: |
                 <?xml version="1.0" encoding="UTF-8"?>
                 <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                     <soapenv:Body>
                         <notificationsResponse xmlns="http://soap.sforce.com/2005/09/outbound">
                             <Ack>true</Ack>
                         </notificationsResponse>
                     </soapenv:Body>
                 </soapenv:Envelope>
      DependsOn:
      - MessageHandlerApi
      - ApiGatewayRole

  MessageHandlerApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
        Description: Stage for salesforce message handler API
        RestApiId: !Ref MessageHandlerApi
        DeploymentId: !Ref MessageHandlerAPIDeployment
        StageName: !Sub ${Stage}
    DependsOn: ContactMethod

  MessageHandlerAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
        Description: Deploys the message handler API into an environment/stage
        RestApiId: !Ref MessageHandlerApi
    DependsOn: ContactMethod





