name: Build salesforce-message-handler

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    permissions:
      id-token: write
      contents: read
    name: salesforce-message-handler build
    runs-on: ubuntu-22.04
    steps:
      - name: Env
        run: env

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "sbt"

      - name: Compile and package project
        run: sbt 'set test in assembly := {}' clean assembly

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: salesforce-message-handler
          configPath: ./riff-raff.yaml
          contentDirectories: |
            cfn:
              - ./cfn.yaml
            salesforce-message-handler:
              - ./salesforce-message-handler.jar
